---
abstract: 'Perl module for interacting with the Asterisk Manager Interface'
author:
  - 'Ryan Bullock <rrb3942@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112621'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Asterisk-AMI
no_index:
  directory:
    - t
    - inc
recommends:
  EV: 0
  Net::SSLeay: 0
requires:
  AnyEvent: 5.2
  AnyEvent::Handle: 0
  AnyEvent::Socket: 0
  Carp: 0
  Digest::MD5: 0
  Scalar::Util: 0
  parent: 0
  version: 0
version: v0.2.7_1
